In [1]:
# Importing neccessary packages
import pandas as pd
import numpy as np

In [2]:
# Reading in csv file and converting to pandas dataframe object
csvFile = pd.read_csv('US_COVID_FINAL.csv') #read in covid dataset from the CDC 
states = ["AL","AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", 
          "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"] #list of state Abbreviations we want to include

In [3]:
# Returning dataframe with specific arguments 
df = pd.DataFrame(csvFile, #establish dataframe datatype, with columns matching below
columns=['submission_date', 'state', 'tot_cases','conf_cases','prob_cases','new_case','pnew_case','tot_death','conf_death','prob_death',\
         'new_death','pnew_death','created_at','consent_cases','consent_deaths'])
df['submission_date']= pd.to_datetime(df['submission_date'])#set datatype for dates

In [4]:
# Converting time attribute to date time format
dfTime=df[df['submission_date']>'11/12/2020']
### define condition as cond_
cond=(dfTime["state"].isin(states))#set our condition to sort through the dataset, removing unwanted states and territories
dfTimeReduced=dfTime.loc[cond,:]#locate condition and include values that meet condition

In [5]:
# Viewing dataframe
dfTimeReduced

,submission_date,state,tot_cases,conf_cases,prob_cases,new_case,pnew_case,tot_death,conf_death,prob_death,new_death,pnew_death,created_at,consent_cases,consent_deaths
296,2020-11-13,CO,154038,146023.0,8015.0,6439,157.0,2504,2096.0,408.0,36,0.0,11/14/2020 02:44:40 PM,Agree,Agree
297,2020-11-14,CO,159234,151115.0,8119.0,5196,104.0,2525,2116.0,409.0,21,1.0,11/15/2020 03:12:13 PM,Agree,Agree
298,2020-11-15,CO,163417,155258.0,8159.0,4183,40.0,2546,2137.0,409.0,21,0.0,11/16/2020 06:40:02 PM,Agree,Agree
299,2020-11-16,CO,167713,158864.0,8849.0,4296,690.0,2578,2153.0,425.0,32,16.0,11/17/2020 02:52:47 PM,Agree,Agree
300,2020-11-17,CO,172044,163076.0,8968.0,4331,119.0,2608,2177.0,431.0,30,6.0,11/18/2020 02:57:46 PM,Agree,Agree
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16963,2020-11-15,VT,2889,NaN,NaN,46,0.0,59,NaN,NaN,0,0.0,11/16/2020 06:40:02 PM,Not agree,Not agree
16964,2020-11-16,VT,3008,NaN,NaN,119,0.0,59,NaN,NaN,0,0.0,11/17/2020 02:52:47 PM,Not agree,Not agree
16965,2020-11-17,VT,3104,NaN,NaN,96,0.0,60,NaN,NaN,1,0.0,11/18/2020 02:57:46 PM,Not agree,Not agree
16966,2020-11-18,VT,3161,NaN,NaN,57,0.0,60,NaN,NaN,0,0.0,11/19/2020 03:01:36 PM,Not agree,Not agree
16967,2020-11-19,VT,3310,NaN,NaN,149,0.0,61,NaN,NaN,1,0.0,11/20/2020 03:06:16 PM,Not agree,Not agree

In [6]:
# Output dataframe to csv file
dfTimeReduced.to_csv('covidData.csv')